# Generated by Django 4.2.7 on 2023-12-28 17:32

import django.core.validators
from django.db import migrations, models
import grades.models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_alter_endgrade_value_alter_grade_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endgrade',
            name='value',
            field=models.FloatField(validators=[grades.models.divisible_by_0_5, grades.models.not_1_5, django.core.validators.MinValueValidator(limit_value=1.0), django.core.validators.MaxValueValidator(limit_value=6.0)]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.FloatField(validators=[grades.models.divisible_by_0_5, grades.models.not_1_5, django.core.validators.MinValueValidator(limit_value=1.0), django.core.validators.MaxValueValidator(limit_value=6.0)]),
        ),
    ]
