# Generated by Django 4.2.7 on 2023-11-24 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetimetable',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='coursetimetable',
            unique_together={('period', 'day_of_week', 'lesson_unit', 'room')},
        ),
    ]
