# Generated by Django 4.2.7 on 2023-11-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=3, unique=True)),
                ('capacity', models.PositiveSmallIntegerField()),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
