# Generated by Django 4.2.7 on 2023-11-25 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_students', models.PositiveSmallIntegerField()),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='RecruitmentStrategy',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(0, 'First in first served'), (1, 'Manual')], primary_key=True, serialize=False)),
                ('is_auto_triggered', models.BooleanField()),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'accepted'), (2, 'rejected')], default=0)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('group_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_applications', to='enrollments.groupenrollment')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
