# Generated by Django 4.2.7 on 2023-11-24 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetables', '0001_initial'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.period'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='timetables.coursetimetable'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='enrollment_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='enrollments.enrollment'),
        ),
    ]
