# Generated by Django 4.2.7 on 2023-11-25 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupenrollment',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='enrollments.enrollment'),
        ),
        migrations.AddField(
            model_name='groupenrollment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='timetables.grouptimetable'),
        ),
        migrations.AddField(
            model_name='groupenrollment',
            name='recruitment_strategy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='enrollments.recruitmentstrategy'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.period'),
        ),
    ]
