# Generated by Django 4.2.7 on 2023-11-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupenrollment',
            old_name='group',
            new_name='course_group',
        ),
    ]
