# Generated by Django 4.2.7 on 2023-11-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseenrollment',
            old_name='enrollment_period',
            new_name='enrollment',
        ),
    ]
