# Generated by Django 4.2.7 on 2023-11-24 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_rename_enrollment_period_courseenrollment_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentStrategy',
            fields=[
                ('id', models.CharField(choices=[(0, 'First in first served')], max_length=20, primary_key=True, serialize=False)),
                ('is_auto_triggered', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='recruitment_strategy',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='enrollments.recruitmentstrategy'),
            preserve_default=False,
        ),
    ]
