# Generated by Django 4.2.7 on 2023-11-25 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_alter_groupenrollment_recruitment_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupenrollment',
            name='recruitment_strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrollments.recruitmentstrategy'),
        ),
    ]
