# Generated by Django 4.2.7 on 2023-11-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_recruitmentstrategy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentstrategy',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(0, 'First in first served')], primary_key=True, serialize=False),
        ),
    ]
