# Generated by Django 4.2.7 on 2023-12-29 11:59

from django.db import migrations, models
import django.db.models.deletion
import timetables.models


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
        ('enrollments', '0005_alter_groupenrollment_recruitment_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('period', models.ForeignKey(default=timetables.models.PeriodManager.get_next_period, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='timetables.period')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='groupenrollment',
            name='min_students',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupenrollment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'created'), (1, 'opened'), (2, 'closed'), (3, 'cancelled')], default=0),
        ),
        migrations.AddField(
            model_name='groupenrollment',
            name='enrollment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='group_enrollments', to='enrollments.enrollment'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EnrollmentPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveSmallIntegerField()),
                ('start_date', models.DateTimeField()),
                ('application_deadline', models.DateTimeField()),
                ('decision_deadline', models.DateTimeField()),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='enrollments.enrollment')),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('enrollment', 'stage')},
            },
        ),
    ]
