# Generated by Django 4.2.7 on 2023-11-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_alter_recruitmentstrategy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
