# Generated by Django 4.2.7 on 2023-11-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0006_studentenrollment_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentstrategy',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(0, 'First in first served'), (1, 'Manual')], primary_key=True, serialize=False),
        ),
    ]
