# Generated by Django 4.2.7 on 2023-12-31 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0011_alter_enrollment_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='period',
        ),
    ]
