# Generated by Django 4.2.7 on 2023-12-31 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0012_remove_enrollment_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentphase',
            name='enrollment',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='enrollments.enrollment'),
            preserve_default=False,
        ),
    ]
