# Generated by Django 4.2.7 on 2023-12-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0013_alter_enrollmentphase_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
