# Generated by Django 4.2.7 on 2023-12-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0014_alter_enrollment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupenrollment',
            name='min_students',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
