# Generated by Django 4.2.7 on 2024-01-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0016_alter_enrollmentphase_application_deadline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitmentstrategy',
            old_name='is_auto_triggered',
            new_name='is_auto_accepted',
        ),
    ]
