# Generated by Django 4.2.7 on 2024-01-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0017_rename_is_auto_triggered_recruitmentstrategy_is_auto_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentstrategy',
            name='is_manual_accept',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pending'), (1, 'accepted'), (2, 'rejected'), (3, 'denied')], default=0),
        ),
    ]
