# Generated by Django 4.2.7 on 2024-01-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0019_alter_recruitmentstrategy_is_manual_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentstrategy',
            name='is_auto_accepted',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='recruitmentstrategy',
            name='is_manual_accept',
            field=models.BooleanField(default=0),
        ),
    ]
