# Generated by Django 4.2.7 on 2024-01-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0020_alter_recruitmentstrategy_is_auto_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='joined',
            field=models.BooleanField(default=False),
        ),
    ]
