# Generated by Django 4.2.7 on 2023-11-25 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='timetables.period'),
        ),
    ]
