# Generated by Django 4.2.7 on 2023-12-28 17:32

import django.core.validators
from django.db import migrations, models
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_endnote_value_alter_note_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endnote',
            name='value',
            field=models.FloatField(validators=[notes.models.divisible_by_0_5, notes.models.not_1_5, django.core.validators.MinValueValidator(limit_value=1.0), django.core.validators.MaxValueValidator(limit_value=6.0)]),
        ),
        migrations.AlterField(
            model_name='note',
            name='value',
            field=models.FloatField(validators=[notes.models.divisible_by_0_5, notes.models.not_1_5, django.core.validators.MinValueValidator(limit_value=1.0), django.core.validators.MaxValueValidator(limit_value=6.0)]),
        ),
    ]
